### ISSUE TITLE
PictureSprites don't seem to render on PIXI v4.0.1

### ISSUE THREAD

**Issue by GordoRank** [pixijs/extension-boilerplate#1]
I'm trying to use your PictureSprite plugin in order to learn the plugin structure for PIXI version 4.

I have a scene with several sprites that all work perfectly when they are `PIXI.Sprite` objects.  If I change them to `PIXI.PictureSprite` objects, then nothing is rendered.  

There are no error messages in the console, the sprites simply aren't rendering.  I can only assume that something is wrong in the `PictureRenderer` code.  Perhaps in the `_renderNormal` function.

Any help would be greatly appreciated as PIXI 4 is very unfamiliar to me.

**Comment by GordoRank** [comment]
Well, I have found the reason why.  The vertices never get calculated.  Removing the `this.transform.updated` check solves the issue.

```
PIXI.PictureSprite.prototype._renderWebGL = function (renderer)
{
    this.calculateVertices();
    //use different plugin for rendering
    renderer.setObjectRenderer(renderer.plugins.picture);
    renderer.plugins.picture.render(this);
};
```

**Comment by ivanpopelyshev** [comment]
Oh right :) Yes, That was fixed in pixi-picture but not here.
